# Generated by Django 4.1.3 on 2022-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='About/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(upload_to='Service_icon')),
                ('service_title', models.CharField(max_length=212)),
                ('image', models.ImageField(upload_to='Service')),
                ('service_content', models.TextField()),
            ],
        ),
    ]
