# Generated by Django 4.1.3 on 2022-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='static/Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(upload_to='static/Service_icon'),
        ),
    ]
